// Mock product database - in a real app, this would come from an API
const products = [
  {
    id: 1,
    name: 'Asgaard sofa',
    detail: 'A luxurious and comfortable sofa perfect for your living room.',
    description: 'A luxurious and comfortable sofa perfect for your living room. This elegant piece combines style and comfort with premium materials and expert craftsmanship. The Asgaard sofa features a timeless design that seamlessly blends into any interior setting. Crafted with attention to detail, it offers exceptional comfort for daily use while maintaining its elegant appearance. The premium fabric upholstery ensures durability and easy maintenance, making it an ideal choice for families and individuals who appreciate both style and functionality.',
    price: 2500000,
    originalPrice: 3500000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'discount', text: '-30%' },
    isNew: false,
    category: 'Living Room',
    color: 'Brown',
    material: 'Wood',
    dimensions: '200cm x 85cm x 75cm',
    weight: '45kg',
    inStock: true,
    rating: 4.8,
    reviews: 124,
    sku: 'SS001',
    tags: ['Sofa', 'Chair', 'Home', 'Shop'],
    sizes: ['XS', 'L', 'XL'],
    colors: ['Purple', 'Black', 'Gold'],
    selectedSize: 'L',
    selectedColor: 'Gold'
  },
  {
    id: 2,
    name: 'Leviosa',
    detail: 'A modern and stylish chair that brings elegance to any space.',
    description: 'A modern and stylish chair that brings elegance to any space. Perfect for dining rooms and home offices. The Leviosa chair features a contemporary design with clean lines and sophisticated aesthetics. Its ergonomic construction provides excellent support and comfort for extended sitting periods. The chair is crafted from high-quality materials that ensure longevity and maintain their beauty over time. Whether used in a formal dining setting or as an accent piece in your home office, the Leviosa chair adds a touch of modern sophistication to any room.',
    price: 2500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Dining Room',
    color: 'Black',
    material: 'Metal',
    dimensions: '60cm x 60cm x 85cm',
    weight: '12kg',
    inStock: true,
    rating: 4.6,
    reviews: 89,
    sku: 'SS002',
    tags: ['Chair', 'Dining', 'Home', 'Shop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'White', 'Gray'],
    selectedSize: 'M',
    selectedColor: 'Black'
  },
  {
    id: 3,
    name: 'Lolito',
    detail: 'Luxury big sofa with premium fabric and comfortable seating.',
    description: 'Luxury big sofa with premium fabric and comfortable seating. Perfect for large living rooms. The Lolito sofa represents the pinnacle of luxury furniture design, offering unparalleled comfort and style. This spacious sofa is designed for those who appreciate the finer things in life, featuring premium fabric upholstery that feels as luxurious as it looks. The generous seating area provides ample space for family gatherings or entertaining guests. The sophisticated design includes carefully crafted details such as tufted cushions, elegant piping, and refined proportions that create a statement piece for any living space.',
    price: 7000000,
    originalPrice: 14000000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'discount', text: '-50%' },
    isNew: false,
    category: 'Living Room',
    color: 'Gray',
    material: 'Fabric',
    dimensions: '280cm x 95cm x 85cm',
    weight: '75kg',
    inStock: true,
    rating: 4.9,
    reviews: 203,
    sku: 'SS003',
    tags: ['Sofa', 'Living Room', 'Home', 'Shop'],
    sizes: ['L', 'XL', 'XXL'],
    colors: ['Gray', 'Beige', 'Navy'],
    selectedSize: 'XL',
    selectedColor: 'Gray'
  },
  {
    id: 4,
    name: 'Respira',
    detail: 'Outdoor bar table and stool set perfect for your patio or garden.',
    description: 'Outdoor bar table and stool set perfect for your patio or garden. The Respira collection brings the comfort and style of indoor furniture to your outdoor living space. This versatile bar table and stool set is designed to withstand the elements while providing a comfortable and stylish seating solution. The weather-resistant materials ensure durability and easy maintenance, making it perfect for year-round use. The modern design features clean lines and contemporary aesthetics that complement any outdoor décor. Whether you\'re hosting a summer barbecue or enjoying a quiet evening under the stars, the Respira set provides the perfect gathering spot for friends and family.',
    price: 500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'new', text: 'New' },
    isNew: true,
    category: 'Outdoor',
    color: 'White',
    material: 'Metal',
    dimensions: '120cm x 60cm x 110cm',
    weight: '25kg',
    inStock: true,
    rating: 4.7,
    reviews: 67,
    sku: 'SS004',
    tags: ['Outdoor', 'Table', 'Home', 'Shop'],
    sizes: ['M', 'L'],
    colors: ['White', 'Black', 'Silver'],
    selectedSize: 'L',
    selectedColor: 'White'
  },
  {
    id: 5,
    name: 'Grifo',
    detail: 'Elegant night lamp with modern design and warm lighting.',
    description: 'Elegant night lamp with modern design and warm lighting. The Grifo night lamp combines sophisticated design with practical functionality to create the perfect ambient lighting solution for your bedroom. This beautifully crafted lamp features a modern silhouette that adds a touch of elegance to any bedside table. The warm, diffused lighting creates a cozy atmosphere perfect for reading or winding down at the end of the day. The lamp\'s glass construction allows light to filter through beautifully, creating a soft, inviting glow. The compact design makes it ideal for smaller spaces while still providing adequate illumination. Whether used as a reading light or ambient mood lighting, the Grifo lamp enhances the comfort and style of your personal sanctuary.',
    price: 1500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Bedroom',
    color: 'White',
    material: 'Glass',
    dimensions: '30cm x 30cm x 60cm',
    weight: '3kg',
    inStock: true,
    rating: 4.5,
    reviews: 45,
    sku: 'SS005',
    tags: ['Lamp', 'Bedroom', 'Home', 'Shop'],
    sizes: ['S', 'M'],
    colors: ['White', 'Black', 'Gold'],
    selectedSize: 'M',
    selectedColor: 'White'
  },
  {
    id: 6,
    name: 'Muggo',
    detail: 'Small ceramic mug perfect for your morning coffee.',
    description: 'Small ceramic mug perfect for your morning coffee. The Muggo mug combines functionality with elegant design to enhance your daily coffee ritual. Crafted from high-quality ceramic, this mug features a comfortable grip and the perfect size for your favorite hot beverages. The smooth, glazed finish ensures easy cleaning and maintains its beautiful appearance over time. Whether you prefer coffee, tea, or hot chocolate, the Muggo mug provides the ideal vessel for your morning routine. Its timeless design makes it a perfect addition to any kitchen collection.',
    price: 150000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'new', text: 'New' },
    isNew: true,
    category: 'Kitchen',
    color: 'White',
    material: 'Ceramic',
    dimensions: '10cm x 8cm x 12cm',
    weight: '0.3kg',
    inStock: true,
    rating: 4.3,
    reviews: 78,
    sku: 'SS006',
    tags: ['Mug', 'Kitchen', 'Home', 'Shop'],
    sizes: ['S', 'M'],
    colors: ['White', 'Black', 'Blue'],
    selectedSize: 'M',
    selectedColor: 'White'
  },
  {
    id: 7,
    name: 'Pingky',
    detail: 'Cute bed set perfect for kids room decoration.',
    description: 'Cute bed set perfect for kids room decoration. The Pingky bed set brings joy and comfort to your child\'s bedroom with its playful design and soft, high-quality materials. This adorable bedding collection features vibrant colors and fun patterns that children love, while maintaining the durability needed for daily use. The set includes a comforter, pillowcases, and fitted sheet, all crafted from hypoallergenic materials that are gentle on sensitive skin. The easy-care fabric ensures simple maintenance for busy parents. Transform your child\'s room into a magical space with the Pingky bed set.',
    price: 7000000,
    originalPrice: 14000000,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'discount', text: '-50%' },
    isNew: false,
    category: 'Kids Room',
    color: 'Pink',
    material: 'Fabric',
    dimensions: '200cm x 150cm',
    weight: '2kg',
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sku: 'SS007',
    tags: ['Bedding', 'Kids', 'Home', 'Shop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Pink', 'Blue', 'Yellow'],
    selectedSize: 'L',
    selectedColor: 'Pink'
  },
  {
    id: 8,
    name: 'Potty',
    detail: 'Minimalist flower pot for modern home decoration.',
    description: 'Minimalist flower pot for modern home decoration. The Potty flower pot embodies the principles of minimalist design while providing the perfect home for your plants. This elegantly crafted pot features clean lines and a neutral color palette that complements any interior style. The durable ceramic construction ensures proper drainage and root health for your plants, while the timeless design makes it a beautiful decorative element even when empty. Whether used indoors or outdoors, the Potty pot adds a touch of natural beauty to your living space.',
    price: 500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: { type: 'new', text: 'New' },
    isNew: true,
    category: 'Outdoor',
    color: 'Green',
    material: 'Ceramic',
    dimensions: '20cm x 20cm x 25cm',
    weight: '1.5kg',
    inStock: true,
    rating: 4.4,
    reviews: 92,
    sku: 'SS008',
    tags: ['Pot', 'Outdoor', 'Home', 'Shop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Green', 'White', 'Terracotta'],
    selectedSize: 'M',
    selectedColor: 'Green'
  },
  {
    id: 9,
    name: 'Syltherine',
    detail: 'Stylish cafe chair with modern design.',
    description: 'Stylish cafe chair with modern design. The Syltherine cafe chair combines contemporary aesthetics with exceptional comfort, making it perfect for both commercial and residential use. This elegant chair features a sleek silhouette with ergonomic design that provides excellent support during extended sitting periods. The high-quality materials ensure durability and easy maintenance, while the sophisticated design adds a touch of elegance to any space. Whether used in a cafe, restaurant, or home dining area, the Syltherine chair creates an inviting atmosphere.',
    price: 2500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Office',
    color: 'Brown',
    material: 'Wood',
    dimensions: '45cm x 45cm x 85cm',
    weight: '8kg',
    inStock: true,
    rating: 4.6,
    reviews: 134,
    sku: 'SS009',
    tags: ['Chair', 'Office', 'Home', 'Shop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Brown', 'Black', 'White'],
    selectedSize: 'M',
    selectedColor: 'Brown'
  },
  {
    id: 10,
    name: 'Leviosa Pro',
    detail: 'Professional dining chair with premium materials.',
    description: 'Professional dining chair with premium materials. The Leviosa Pro represents the next generation of dining chairs, combining luxury with functionality. This premium chair features advanced ergonomic design and high-quality materials that ensure both comfort and durability. The sophisticated construction includes reinforced joints and premium upholstery that maintains its beauty over time. Perfect for formal dining rooms or upscale restaurants, the Leviosa Pro creates an atmosphere of elegance and sophistication.',
    price: 2500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Dining Room',
    color: 'Black',
    material: 'Metal',
    dimensions: '50cm x 50cm x 90cm',
    weight: '10kg',
    inStock: true,
    rating: 4.8,
    reviews: 89,
    sku: 'SS010',
    tags: ['Chair', 'Dining', 'Home', 'Shop'],
    sizes: ['M', 'L'],
    colors: ['Black', 'White', 'Gray'],
    selectedSize: 'L',
    selectedColor: 'Black'
  },
  {
    id: 11,
    name: 'Lolito Premium',
    detail: 'Premium leather sofa with luxury comfort.',
    description: 'Premium leather sofa with luxury comfort. The Lolito Premium represents the ultimate in luxury seating, featuring genuine leather upholstery and superior craftsmanship. This exceptional sofa combines timeless design with modern comfort, creating a centerpiece for any sophisticated living space. The premium leather not only looks luxurious but also ages beautifully, developing a rich patina over time. The advanced cushioning system provides unparalleled comfort while maintaining its shape and support for years to come.',
    price: 7000000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Living Room',
    color: 'Beige',
    material: 'Leather',
    dimensions: '300cm x 100cm x 90cm',
    weight: '85kg',
    inStock: true,
    rating: 4.9,
    reviews: 203,
    sku: 'SS011',
    tags: ['Sofa', 'Living Room', 'Home', 'Shop'],
    sizes: ['L', 'XL', 'XXL'],
    colors: ['Beige', 'Brown', 'Black'],
    selectedSize: 'XL',
    selectedColor: 'Beige'
  },
  {
    id: 12,
    name: 'Respira Deluxe',
    detail: 'Deluxe outdoor dining set for elegant outdoor living.',
    description: 'Deluxe outdoor dining set for elegant outdoor living. The Respira Deluxe collection elevates outdoor dining to new heights of sophistication and comfort. This premium outdoor furniture set includes a dining table and matching chairs, all crafted from weather-resistant materials that maintain their beauty season after season. The elegant design features clean lines and contemporary styling that complements any outdoor space. Perfect for entertaining guests or enjoying family meals al fresco, the Respira Deluxe set creates an outdoor dining experience that rivals the finest indoor settings.',
    price: 500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Outdoor',
    color: 'White',
    material: 'Metal',
    dimensions: '180cm x 90cm x 75cm',
    weight: '35kg',
    inStock: true,
    rating: 4.7,
    reviews: 67,
    sku: 'SS012',
    tags: ['Outdoor', 'Dining', 'Home', 'Shop'],
    sizes: ['L', 'XL'],
    colors: ['White', 'Black', 'Silver'],
    selectedSize: 'L',
    selectedColor: 'White'
  },
  {
    id: 13,
    name: 'Grifo Classic',
    detail: 'Classic table lamp with timeless design.',
    description: 'Classic table lamp with timeless design. The Grifo Classic lamp embodies the elegance of traditional design while incorporating modern functionality. This beautifully crafted table lamp features a classic silhouette that never goes out of style, making it a perfect addition to any room. The warm, ambient lighting creates a cozy atmosphere perfect for reading, working, or simply relaxing. The lamp\'s construction ensures years of reliable use while maintaining its sophisticated appearance.',
    price: 1500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Bedroom',
    color: 'White',
    material: 'Glass',
    dimensions: '25cm x 25cm x 50cm',
    weight: '2.5kg',
    inStock: true,
    rating: 4.5,
    reviews: 45,
    sku: 'SS013',
    tags: ['Lamp', 'Bedroom', 'Home', 'Shop'],
    sizes: ['S', 'M'],
    colors: ['White', 'Black', 'Gold'],
    selectedSize: 'M',
    selectedColor: 'White'
  },
  {
    id: 14,
    name: 'Muggo Deluxe',
    detail: 'Deluxe ceramic mug set for coffee enthusiasts.',
    description: 'Deluxe ceramic mug set for coffee enthusiasts. The Muggo Deluxe collection offers the perfect combination of style and functionality for coffee lovers. This premium mug set features high-quality ceramic construction with a beautiful glaze that enhances the drinking experience. Each mug is carefully crafted to provide the perfect temperature retention and comfortable grip. The elegant design makes these mugs suitable for both everyday use and special occasions.',
    price: 150000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Kitchen',
    color: 'White',
    material: 'Ceramic',
    dimensions: '12cm x 10cm x 15cm',
    weight: '0.4kg',
    inStock: true,
    rating: 4.3,
    reviews: 78,
    sku: 'SS014',
    tags: ['Mug', 'Kitchen', 'Home', 'Shop'],
    sizes: ['M', 'L'],
    colors: ['White', 'Black', 'Blue'],
    selectedSize: 'L',
    selectedColor: 'White'
  },
  {
    id: 15,
    name: 'Pingky Dream',
    detail: 'Dreamy bedding set for peaceful sleep.',
    description: 'Dreamy bedding set for peaceful sleep. The Pingky Dream collection creates the perfect environment for restful sleep with its soft, breathable materials and calming designs. This premium bedding set includes everything needed for a comfortable night\'s rest, from the softest cotton sheets to a cozy comforter. The gentle colors and patterns promote relaxation while the high-quality materials ensure durability and easy care. Transform your bedroom into a peaceful sanctuary with the Pingky Dream bedding collection.',
    price: 7000000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Kids Room',
    color: 'Pink',
    material: 'Fabric',
    dimensions: '220cm x 160cm',
    weight: '2.5kg',
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sku: 'SS015',
    tags: ['Bedding', 'Kids', 'Home', 'Shop'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Pink', 'Blue', 'Yellow'],
    selectedSize: 'L',
    selectedColor: 'Pink'
  },
  {
    id: 16,
    name: 'Potty Artisan',
    detail: 'Artisan-crafted flower pot with unique design.',
    description: 'Artisan-crafted flower pot with unique design. The Potty Artisan collection showcases the beauty of handcrafted ceramics, with each piece bearing the unique touch of skilled artisans. These beautiful flower pots feature intricate designs and premium materials that make them stand out as decorative pieces in their own right. The careful craftsmanship ensures proper drainage and optimal growing conditions for your plants, while the artistic designs add character and charm to any space.',
    price: 500000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop'
    ],
    badge: null,
    isNew: false,
    category: 'Outdoor',
    color: 'Green',
    material: 'Ceramic',
    dimensions: '25cm x 25cm x 30cm',
    weight: '2kg',
    inStock: true,
    rating: 4.4,
    reviews: 92,
    sku: 'SS016',
    tags: ['Pot', 'Outdoor', 'Home', 'Shop'],
    sizes: ['M', 'L'],
    colors: ['Green', 'White', 'Terracotta'],
    selectedSize: 'L',
    selectedColor: 'Green'
  }
];

export const getProductById = (id) => {
  return products.find(product => product.id === parseInt(id)) || null;
};

export const getAllProducts = () => {
  return products;
};

export const getProductsByCategory = (category) => {
  return products.filter(product => product.category === category);
};

export const searchProducts = (query) => {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(product => 
    product.name.toLowerCase().includes(lowercaseQuery) ||
    product.description.toLowerCase().includes(lowercaseQuery) ||
    product.category.toLowerCase().includes(lowercaseQuery)
  );
}; 